import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import Navbar from "@/components/Navbar";
import LeftSideBar from "@/components/LeftSideBar";
import BottomBar from "@/components/BottomBar";
import {ToastContainer} from "../components/NextToast"
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
          >
            <LeftSideBar/>
            <Navbar/>            
            <BottomBar/>
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
