import type { Metadata } from "next";
import "../../globals.css";
import { ThemeProvider } from "@/components/theme-provider"


export const metadata: Metadata = {
    title: "Create Post | SnapGram",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
        >
            <div className=' px-5 py-5 mb-[30px]'>
                {children}
            </div>
        </ThemeProvider>
    );
}
