import mongoose, { Schema } from "mongoose";

const userSchema = new Schema({
    firstName:{
        type:String,
        required:true
    },
    lastName:{
        type:String,
        required:true
    },
    userName:{
        type:String,
        required:true,
        unique:true
    },
    email:{
        type:String,
        required:true
    },
    password:{
        type:String,
        required:true
    },
    active:{
        type:Boolean,
    },
    lastActiveTime:{
        type:Date,
    },
    posts:[
        {
            type:mongoose.Schema.ObjectId,
            ref:'Post'
        }
    ],
    likedPost:[
        {
            type:mongoose.Schema.ObjectId,
            ref:'Post'
        }
    ],
    savedPosts:[
        {
            type:mongoose.Schema.ObjectId,
            ref:'Post'
        }
    ],
    followers:[
        {
            type:mongoose.Schema.ObjectId,
            ref:'User'
        }
    ],
    following:[
        {
            type:mongoose.Schema.ObjectId,
            ref:'User'
        }
    ],
    profileImage:{
        type:String,
        default:''
    },
    notification:[
        {
            type:String,
        }
    ],
    notificationDp:[
        {
            type:String,
        }
    ],
    userNotificationId:[
        {
            type:String,
        }
    ]
})

export const User = mongoose.models?.User || mongoose.model('User',userSchema)